package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno extends Usuarios implements java.io.Serializable {


     private Integer id;
     private Carrera carrera;
     private Usuarios usuarios;
     private Integer beca;
     private Set cursos = new HashSet(0);
     private Set notas = new HashSet(0);

    public Alumno(){
        super();
    }

    public Alumno(Integer id, Carrera carrera, Usuarios usuarios, Integer beca, String cedula, String nombre, String clave, String email, Date fechaNac, Integer type, Set matriculadors, Set administradors, Set profesors, Set alumnos) {
        super(cedula, nombre, clave, email, fechaNac, type, matriculadors, administradors, profesors, alumnos);
        this.id = id;
        this.carrera = carrera;
        this.usuarios = usuarios;
        this.beca = beca;
    }

    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getBeca() {
        return this.beca;
    }
    
    public void setBeca(Integer beca) {
        this.beca = beca;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }




}


