package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String nombre;
     private String titulo;
     private Set cursos = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Carrera() {
    }

    public Carrera(String codigo, String nombre, String titulo, Set cursos, Set alumnos) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.titulo = titulo;
       this.cursos = cursos;
       this.alumnos = alumnos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


