package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo  implements java.io.Serializable {


     private Integer id;
     private int anyo;
     private int numero;
     private Date fechaInit;
     private String fechaFin;
     private Set cursos = new HashSet(0);

    public Ciclo() {
    }

	
    public Ciclo(int anyo, int numero) {
        this.anyo = anyo;
        this.numero = numero;
    }
    public Ciclo(int anyo, int numero, Date fechaInit, String fechaFin, Set cursos) {
       this.anyo = anyo;
       this.numero = numero;
       this.fechaInit = fechaInit;
       this.fechaFin = fechaFin;
       this.cursos = cursos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAnyo() {
        return this.anyo;
    }
    
    public void setAnyo(int anyo) {
        this.anyo = anyo;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Date getFechaInit() {
        return this.fechaInit;
    }
    
    public void setFechaInit(Date fechaInit) {
        this.fechaInit = fechaInit;
    }
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


