package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer id;
     private Carrera carrera;
     private Ciclo ciclo;
     private String codigo;
     private String nombre;
     private Integer creditos;
     private Integer horasSemanles;
     private Set alumnos = new HashSet(0);
     private Set grupos = new HashSet(0);
     private Set notas = new HashSet(0);

    public Curso() {
    }

    public Curso(Carrera carrera, Ciclo ciclo, String codigo, String nombre, Integer creditos, Integer horasSemanles, Set alumnos, Set grupos, Set notas) {
       this.carrera = carrera;
       this.ciclo = ciclo;
       this.codigo = codigo;
       this.nombre = nombre;
       this.creditos = creditos;
       this.horasSemanles = horasSemanles;
       this.alumnos = alumnos;
       this.grupos = grupos;
       this.notas = notas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Integer creditos) {
        this.creditos = creditos;
    }
    public Integer getHorasSemanles() {
        return this.horasSemanles;
    }
    
    public void setHorasSemanles(Integer horasSemanles) {
        this.horasSemanles = horasSemanles;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }




}


