package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1



/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int id;
     private Curso curso;
     private Integer numeroGrupo;
     private String horario;

    public Grupo() {
    }

	
    public Grupo(int id) {
        this.id = id;
    }
    public Grupo(int id, Curso curso, Integer numeroGrupo, String horario) {
       this.id = id;
       this.curso = curso;
       this.numeroGrupo = numeroGrupo;
       this.horario = horario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Integer getNumeroGrupo() {
        return this.numeroGrupo;
    }
    
    public void setNumeroGrupo(Integer numeroGrupo) {
        this.numeroGrupo = numeroGrupo;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }




}


