package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;

/**
 * Matriculador generated by hbm2java
 */
public class Matriculador extends Usuarios  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuarios;
     private Date fechaIni;
     private Date fechaFin;

    public Matriculador() {
        super();
    }

    public Matriculador(Integer id, Usuarios usuarios, Date fechaIni, Date fechaFin, String cedula, String nombre, String clave, String email, Date fechaNac, Integer type, Set matriculadors, Set administradors, Set profesors, Set alumnos) {
        super(cedula, nombre, clave, email, fechaNac, type, matriculadors, administradors, profesors, alumnos);
        this.id = id;
        this.usuarios = usuarios;
        this.fechaIni = fechaIni;
        this.fechaFin = fechaFin;
    }

    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


