package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1



/**
 * Nota generated by hbm2java
 */
public class Nota  implements java.io.Serializable {


     private int id;
     private Alumno alumno;
     private Curso curso;
     private String nota;
     private Integer historial;

    public Nota() {
    }

	
    public Nota(int id) {
        this.id = id;
    }
    public Nota(int id, Alumno alumno, Curso curso, String nota, Integer historial) {
       this.id = id;
       this.alumno = alumno;
       this.curso = curso;
       this.nota = nota;
       this.historial = historial;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public Integer getHistorial() {
        return this.historial;
    }
    
    public void setHistorial(Integer historial) {
        this.historial = historial;
    }




}


