package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;




/**
 * Profesor generated by hbm2java
 */
public class Profesor extends Usuarios implements java.io.Serializable {


     private Integer id;
     private Usuarios usuarios;
     private String categoria;
     private Double salario;

    public Profesor() {
        super();
    }

    public Profesor(Integer id, Usuarios usuarios, String categoria, Double salario, String cedula, String nombre, String clave, String email, Date fechaNac, Integer type, Set matriculadors, Set administradors, Set profesors, Set alumnos) {
        super(cedula, nombre, clave, email, fechaNac, type, matriculadors, administradors, profesors, alumnos);
        this.id = id;
        this.usuarios = usuarios;
        this.categoria = categoria;
        this.salario = salario;
    }

    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }




}


