package LogicaNegocio;
// Generated Mar 3, 2017 5:54:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private String cedula;
     private String nombre;
     private String clave;
     private String email;
     private Date fechaNac;
     private Integer type;
     private Set matriculadors = new HashSet(0);
     private Set administradors = new HashSet(0);
     private Set profesors = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Usuarios() {
    }

    public Usuarios(String cedula, String nombre, String clave, String email, Date fechaNac, Integer type, Set matriculadors, Set administradors, Set profesors, Set alumnos) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.clave = clave;
       this.email = email;
       this.fechaNac = fechaNac;
       this.type = type;
       this.matriculadors = matriculadors;
       this.administradors = administradors;
       this.profesors = profesors;
       this.alumnos = alumnos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Set getMatriculadors() {
        return this.matriculadors;
    }
    
    public void setMatriculadors(Set matriculadors) {
        this.matriculadors = matriculadors;
    }
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


